### ISSUE TITLE
Wrong PP values

### ISSUE THREAD

**Issue by takoz53** [grumd/osu-pps#10]
e.g. [Dancing Dolls - monochrome(Asterisk Makina Remix) [Scythe]](http://osu.ppy.sh/b/770576) **+HDHR**

**417PP** in **Bancho** | **376PP** in **osu-pps**.

Perhaps implementing an auto-pp calculator from **[osu-lazer GitHub](https://github.com/ppy/osu/blob/master/osu.Game.Rulesets.Osu/Difficulty/OsuPerformanceCalculator.cs)** might be good for maintaining proper pp values automatically.

**Comment by grumd** [comment]
@takoz53 I can't use an accurate pp calculator because to calculate pp values you need to download .osu file, and that would take A LOT more time and traffic for me. 

376pp is osu-pps is the AVERAGE pp people get for this map. Nothing fancy.

**Comment by takoz53** [comment]
Oh. I haven't checked the code so I thought It was not up to date. If so I'll close this issue. Thanks for the quick answer 👍
