### ISSUE TITLE
Not up-to-date & cannot find more data about mappers

### ISSUE THREAD

**Issue by IceCandle** [grumd/osu-pps#16]
If you go to https://osu-pps.com, you can see that the data was last updated on April 22 or 23rd, 2020. Also according to the last commit, more information about the mapper was added, including the number of favorites and playcount, but I can't find it anywhere.

**Comment by grumd** [comment]
@IceCandle yeah thanks, I restarted my update service and it works again.

btw next time use "contact:" links from the website to contact me. i'm not checking github very often

**Comment by grumd** [comment]
@IceCandle about more information about the mapper... you've probably found it in `develop` branch which is for developing. it's not on the website yet and it's a work in progress. i'm planning to add a new section for mappers in the future. and also planning on adding a new filter for the main page that lets you only view maps ranked in the last week/month/3months etc
