### ISSUE TITLE
[Enhancement] Table first row should move along.

### ISSUE THREAD

**Issue by takoz53** [grumd/osu-pps#26]
Would be cool if this whole table would move along when you scroll down as you have to else remember, which column was HR, which one FL etc.

[Table I speak of](https://puu.sh/HExTH/c95c5e8d76.png)

**Comment by grumd** [comment]
![image](https://user-images.githubusercontent.com/5869818/118366156-3730a480-b5a8-11eb-97cb-be0435cfc671.png)

I did this instead
