### ISSUE TITLE
Incorrect difficulty name and value

### ISSUE THREAD

**Issue by acrylic-style** [grumd/osu-pps#7]
## Difficulty Name
Go to (site)[https://grumd.github.io/osu-pps/#/maps] and search by `speed of link 450`
Correct difficulty name is `450 000m/s` but this site says `450`
![image](https://user-images.githubusercontent.com/19150229/54075683-6a4ebd80-42e5-11e9-96a0-8d8db20ecafb.png)

## Difficulty Value
Not compatible with pp-rebalance update? It shows `3.98` but correct value is `4.32`
![image](https://user-images.githubusercontent.com/19150229/54075733-08428800-42e6-11e9-8f7b-4ec289e0d9c0.png)
![image](https://user-images.githubusercontent.com/19150229/54075741-17c1d100-42e6-11e9-9fcc-c4a56edf95c0.png)

**Comment by grumd** [comment]
lol thanks I found the issue with the diff name. star rating is old probably because i didn't clear cache, I will clear cache and try again

**Comment by grumd** [comment]
will be fixed in the next release
