### ISSUE TITLE
overweightness values don't match at all between maps and mapeprs

### ISSUE THREAD

**Issue by SuperStormer** [grumd/osu-pps#81]
I might be missing something, but none of the overweightness values match between maps in the mappers tab, and the corresponding entry in the maps tab.

For example, Zan'ei has 6596.7 overweightness points in the mappers tab:
![image](https://user-images.githubusercontent.com/41648788/190883480-80d73aab-f5cf-402e-8dc2-0a967d7c68bb.png)

but virtually no overweightness points in the maps tab:
![image](https://user-images.githubusercontent.com/41648788/190883493-bc206508-74fe-4437-b316-24a018655dc5.png)

I have tried clearing site data, but the discrepancy remains.

**Comment by grumd** [comment]
oh shit something broke last update xD

**Comment by grumd** [comment]
I'll go see what's wrong

**Comment by grumd** [comment]
I'll roll back the data for now, and will investigate why the numbers went bonkers

**Comment by grumd** [comment]
It's fixed, an update just went in for std and mania, the rest will come shortly
